export const fundTypeList = [
  {
    title: '混合型',
    value: 'mixed',
    key: 'mixed',
    children: [
      {
        fundType: '混合型',
        value: '160910.SZ',
        key: '160910.SZ',
        fundManager: '******',
        fundManageMentComp: '大成基金',
        fundShare: 2192943.9351,
        title: '大成创新成长混合型证券投资基金(LOF)',
      },
      {
        fundType: '混合型',
        value: '050009.OF',
        key: '050009.OF',
        fundManager: '******',
        fundManageMentComp: '博时基金',
        fundShare: 202338.363198,
        title: '博时新兴成长混合型证券投资基金',
      },
      {
        fundType: '混合型',
        value: '160805.SZ',
        key: '160805.SZ',
        fundManager: '******',
        fundManageMentComp: '长盛基金',
        fundShare: 1179412.057,
        title: '长盛同智优势成长混合型证券投资基金(LOF)',
      },
      {
        fundType: '混合型',
        value: '160311.SZ',
        key: '160311.SZ',
        fundManager: '******',
        fundManageMentComp: '华夏基金',
        fundShare: 1113059.0981,
        title: '华夏蓝筹核心混合型证券投资基金(LOF)',
      },
      {
        fundType: '混合型',
        value: '202005.OF',
        key: '202005.OF',
        fundManager: '******',
        fundManageMentComp: '南方基金',
        fundShare: 388906.205123,
        title: '南方成份精选混合型证券投资基金',
      },
      {
        fundType: '混合型',
        value: '050008.OF',
        key: '050008.OF',
        fundManager: '******',
        fundManageMentComp: '博时基金',
        fundShare: 110253.226696,
        title: '博时第三产业成长混合型证券投资基金',
      },
      {
        fundType: '混合型',
        value: '519021.OF',
        key: '519021.OF',
        fundManager: '******',
        fundManageMentComp: '国泰基金',
        fundShare: 144526.908882,
        title: '国泰金鼎价值精选混合型证券投资基金',
      },
      {
        fundType: '混合型',
        value: '519035.OF',
        key: '519035.OF',
        fundManager: '******',
        fundManageMentComp: '富国基金',
        fundShare: 101773.242423,
        title: '富国天博创新主题混合型证券投资基金',
      },
      {
        fundType: '混合型',
        value: '006296.OF',
        key: '006296.OF',
        fundManager: '******',
        fundManageMentComp: '鹏华基金',
        fundShare: 10782.401707,
        title: '鹏华养老目标日期2035三年持有期混合型基金中基金(FOF)',
      },
      {
        fundType: '混合型',
        value: '012953.OF',
        key: '012953.OF',
        fundManager: '******',
        fundManageMentComp: '华泰柏瑞基金',
        fundShare: 39336.828114,
        title: '华泰柏瑞恒利混合型证券投资基金',
      },
    ],
  },
  {
    title: '股票型',
    value: 'stock',
    key: 'stock',
    children: [
      {
        fundType: '股票型',
        fundCode: '006329.OF',
        fundManager: '******',
        fundManageMentComp: '易方达基金',
        fundShare: 992922.783238,
        fundName:
          '易方达中证海外中国互联网50交易型开放式指数证券投资基金联接基金',
      },
      {
        fundType: '股票型',
        fundCode: '011861.OF',
        fundManager: '******',
        fundManageMentComp: '南方基金',
        fundShare: 72217.773352,
        fundName: '南方中证1000交易型开放式指数证券投资基金发起式联接基金',
      },
      {
        fundType: '股票型',
        fundCode: '012643.OF',
        fundManager: '******',
        fundManageMentComp: '招商基金',
        fundShare: 46335.169051,
        fundName: '招商中证红利交易型开放式指数证券投资基金联接基金',
      },
      {
        fundType: '股票型',
        fundCode: '005961.OF',
        fundManager: '******',
        fundManageMentComp: '博时基金',
        fundShare: 4504.049716,
        fundName: '博时量化价值股票型证券投资基金',
      },
      {
        fundType: '股票型',
        fundCode: '501031.SH',
        fundManager: '******',
        fundManageMentComp: '汇添富基金',
        fundShare: 31182.165045,
        fundName: '汇添富中证环境治理指数型证券投资基金(LOF)',
      },
      {
        fundType: '股票型',
        fundCode: '011343.OF',
        fundManager: '******',
        fundManageMentComp: '德邦基金',
        fundName: '德邦创业板指数增强型证券投资基金',
      },
      {
        fundType: '股票型',
        fundCode: '501221.OF',
        fundManager: '******',
        fundManageMentComp: '民生加银基金',
        fundName: '民生加银优享进取一年封闭运作股票型基金中基金(FOF-LOF)',
      },
      {
        fundType: '股票型',
        fundCode: '015891.OF',
        fundManager: '******',
        fundManageMentComp: '富国基金',
        fundShare: 38017.225459,
        fundName: '富国上证50基本面精选股票型发起式证券投资基金',
      },
      {
        fundType: '股票型',
        fundCode: '018397.OF',
        fundManager: '******',
        fundManageMentComp: '博时基金',
        fundShare: 3250.189704,
        fundName: '博时中证医疗指数型发起式证券投资基金',
      },
      {
        fundType: '股票型',
        fundCode: '588050.SH',
        fundManager: '******',
        fundManageMentComp: '工银瑞信基金',
        fundShare: 1443124.13,
        fundName: '工银瑞信上证科创板50成份交易型开放式指数证券投资基金',
      },
      {
        fundType: '股票型',
        fundCode: '512010.SH',
        fundManager: '******',
        fundManageMentComp: '易方达基金',
        fundShare: 6479869.49,
        fundName: '易方达沪深300医药卫生交易型开放式指数证券投资基金',
      },
      {
        fundType: '股票型',
        fundCode: '017916.OF',
        fundManager: '******',
        fundManageMentComp: '国寿安保基金',
        fundShare: 25541.009092,
        fundName: '国寿安保成长优选股票型证券投资基金',
      },
    ].map((e) => ({
      key: e.fundCode,
      value: e.fundCode,
      title: e.fundName,
    })),
  },
  {
    title: '债券型',
    value: 'bond',
    key: 'bond',
    children: [
      {
        fundType: '债券型',
        fundCode: '015167.OF',
        fundManager: '******',
        fundManageMentComp: '申万菱信基金',
        fundShare: 620.456262,
        fundName: '申万菱信可转换债券债券型证券投资基金',
      },
      {
        fundType: '债券型',
        fundCode: '017055.OF',
        fundManager: '******',
        fundManageMentComp: '工银瑞信基金',
        fundShare: 490101.575223,
        fundName: '工银瑞信稳健丰润90天持有期中短债债券型证券投资基金',
      },
      {
        fundType: '债券型',
        fundCode: '005951.OF',
        fundManager: '******',
        fundManageMentComp: '民生加银基金',
        fundShare: 534273.655878,
        fundName: '民生加银恒益纯债债券型证券投资基金',
      },
      {
        fundType: '债券型',
        fundCode: '003349.OF',
        fundManager: '******',
        fundManageMentComp: '长信基金',
        fundShare: 103147.043387,
        fundName: '长信稳益纯债债券型证券投资基金',
      },
      {
        fundType: '债券型',
        fundCode: '003788.OF',
        fundManager: '******',
        fundManageMentComp: '方正富邦基金',
        fundShare: 1595.843906,
        fundName: '方正富邦惠利纯债债券型证券投资基金',
      },
      {
        fundType: '债券型',
        fundCode: '005929.OF',
        fundManager: '******',
        fundManageMentComp: '创金合信基金',
        fundName: '创金合信汇利纯债三年期定期开放债券型证券投资基金',
      },
      {
        fundType: '债券型',
        fundCode: '008877.OF',
        fundManager: '******',
        fundManageMentComp: '国联安基金',
        fundShare: 79113.173108,
        fundName: '国联安增盛一年定期开放纯债债券型发起式证券投资基金',
      },
      {
        fundType: '债券型',
        fundCode: '012789.OF',
        fundManager: '******',
        fundManageMentComp: '汇添富基金',
        fundShare: 212343.42761,
        fundName: '汇添富双享回报债券型证券投资基金',
      },
      {
        fundType: '债券型',
        fundCode: '013538.OF',
        fundManager: '******',
        fundManageMentComp: '鹏华基金',
        fundShare: 39659.786982,
        fundName: '鹏华永宁3个月定期开放债券型证券投资基金',
      },
      {
        fundType: '债券型',
        fundCode: '018206.OF',
        fundManager: '******',
        fundManageMentComp: '永赢基金',
        fundShare: 645193.322574,
        fundName: '永赢浩益一年定期开放债券型发起式证券投资基金',
      },
      {
        fundType: '债券型',
        fundCode: '001783.OF',
        fundManager: '******',
        fundManageMentComp: '兴银基金',
        fundShare: 495640.068877,
        fundName: '兴银合盈债券型证券投资基金',
      },
      {
        fundType: '债券型',
        fundCode: '002143.OF',
        fundManager: '******',
        fundManageMentComp: '博时基金',
        fundShare: 131827.77241,
        fundName: '博时裕坤纯债3个月定期开放债券型发起式证券投资基金',
      },
    ].map((e) => ({
      key: e.fundCode,
      value: e.fundCode,
      title: e.fundName,
    })),
  },
  {
    title: '货币市场型',
    value: 'moneyMarket',
    key: 'moneyMarket',
    children: [
      {
        fundType: '货币市场型',
        fundCode: '003363.OF',
        fundManager: '******',
        fundManageMentComp: '长江资管',
        fundShare: 839899.658536,
        fundName: '长江乐享货币市场基金',
      },
      {
        fundType: '货币市场型',
        fundCode: '003316.OF',
        fundManager: '******',
        fundManageMentComp: '中银证券',
        fundShare: 1043274.77226,
        fundName: '中银证券现金管家货币市场基金',
      },
      {
        fundType: '货币市场型',
        fundCode: '010325.OF',
        fundManager: '******',
        fundManageMentComp: '申万菱信基金',
        fundShare: 37903.327226,
        fundName: '申万菱信收益宝货币市场基金',
      },
      {
        fundType: '货币市场型',
        fundCode: '004787.OF',
        fundManager: '******',
        fundManageMentComp: '渤海汇金资管',
        fundShare: 407215.947743,
        fundName: '渤海汇金汇添金货币市场基金',
      },
      {
        fundType: '货币市场型',
        fundCode: '000846.OF',
        fundManager: '******',
        fundManageMentComp: '国联基金',
        fundShare: 282457.431178,
        fundName: '国联货币市场基金',
      },
      {
        fundType: '货币市场型',
        fundCode: '004938.OF',
        fundManager: '******',
        fundManageMentComp: '中欧基金',
        fundShare: 578.654377,
        fundName: '中欧滚钱宝发起式货币市场基金',
      },
      {
        fundType: '货币市场型',
        fundCode: '002184.OF',
        fundManager: '******',
        fundManageMentComp: '泓德基金',
        fundShare: 5749.399425,
        fundName: '泓德泓利货币市场基金',
      },
      {
        fundType: '货币市场型',
        fundCode: '018202.OF',
        fundManager: '******',
        fundManageMentComp: '中信建投基金',
        fundShare: 6071.461177,
        fundName: '中信建投添鑫宝货币市场基金',
      },
      {
        fundType: '货币市场型',
        fundCode: '163802.OF',
        fundManager: '******',
        fundManageMentComp: '中银基金',
        fundShare: 3338818.053906,
        fundName: '中银货币市场证券投资基金',
      },
      {
        fundType: '货币市场型',
        fundCode: '018408.OF',
        fundManager: '******',
        fundManageMentComp: '南方基金',
        fundShare: 5876.720544,
        fundName: '南方现金增利基金',
      },
      {
        fundType: '货币市场型',
        fundCode: '000829.OF',
        fundManager: '******',
        fundManageMentComp: '易方达基金',
        fundShare: 6239315.899735,
        fundName: '易方达天天发货币市场基金',
      },
      {
        fundType: '货币市场型',
        fundCode: '000581.OF',
        fundManager: '******',
        fundManageMentComp: '嘉实基金',
        fundShare: 8042444.752041,
        fundName: '嘉实活钱包货币市场基金',
      },
    ].map((e) => {
      return {
        key: e.fundCode,
        value: e.fundCode,
        title: e.fundName,
      };
    }),
  },
];

export const managerList = [
  {
    title: '张三',
    value: 'zhangsan',
    key: 'zhangsan',
    children: [
      {
        fundType: '混合型',
        value: '160910.SZ',
        key: '160910.SZ',
        fundManager: '******',
        fundManageMentComp: '大成基金',
        fundShare: 2192943.9351,
        title: '大成创新成长混合型证券投资基金(LOF)',
      },
      {
        fundType: '混合型',
        value: '050009.OF',
        key: '050009.OF',
        fundManager: '******',
        fundManageMentComp: '博时基金',
        fundShare: 202338.363198,
        title: '博时新兴成长混合型证券投资基金',
      },
    ],
  },
  {
    title: '李四',
    value: 'lisi',
    key: 'lisi',
    children: [
      {
        fundType: '混合型',
        value: '160805.SZ',
        key: '160805.SZ',
        fundManager: '******',
        fundManageMentComp: '长盛基金',
        fundShare: 1179412.057,
        title: '长盛同智优势成长混合型证券投资基金(LOF)',
      },
      {
        fundType: '混合型',
        value: '160311.SZ',
        key: '160311.SZ',
        fundManager: '******',
        fundManageMentComp: '华夏基金',
        fundShare: 1113059.0981,
        title: '华夏蓝筹核心混合型证券投资基金(LOF)',
      },
    ],
  },
  {
    title: '王五',
    value: 'wangwu',
    key: 'wangwu',
    children: [
      {
        fundType: '混合型',
        value: '202005.OF',
        key: '202005.OF',
        fundManager: '******',
        fundManageMentComp: '南方基金',
        fundShare: 388906.205123,
        title: '南方成份精选混合型证券投资基金',
      },
      {
        fundType: '混合型',
        value: '050008.OF',
        key: '050008.OF',
        fundManager: '******',
        fundManageMentComp: '博时基金',
        fundShare: 110253.226696,
        title: '博时第三产业成长混合型证券投资基金',
      },
    ],
  },
  {
    title: '赵六',
    value: 'zhaoliu',
    key: 'zhaoliu',
    children: [
      {
        fundType: '混合型',
        value: '519021.OF',
        key: '519021.OF',
        fundManager: '******',
        fundManageMentComp: '国泰基金',
        fundShare: 144526.908882,
        title: '国泰金鼎价值精选混合型证券投资基金',
      },
      {
        fundType: '混合型',
        value: '519035.OF',
        key: '519035.OF',
        fundManager: '******',
        fundManageMentComp: '富国基金',
        fundShare: 101773.242423,
        title: '富国天博创新主题混合型证券投资基金',
      },
    ],
  },
];

export const sectorList = [
  {
    title: '农林牧渔',
    value: 'nlmy',
    key: 'nlmy',
  },
  {
    title: '采掘',
    value: 'cjy',
    key: 'cjy',
  },
  {
    title: '化工',
    value: 'hg',
    key: 'hg',
  },
  {
    title: '钢铁',
    value: 'gt',
    key: 'gt',
  },
  {
    title: '有色金属',
    value: 'ysjs',
    key: 'ysjs',
  },
  {
    title: '电子',
    value: 'dz',
    key: 'dz',
  },
  {
    title: '计算机',
    value: 'jsj',
    key: 'jsj',
  },
  {
    title: '通信',
    value: 'tx',
    key: 'tx',
  },
  {
    title: '传媒',
    value: 'cm',
    key: 'cm',
  },
];

export const conceptList = [
  {
    title: '5G',
    value: '5G',
    key: '5G',
  },
  {
    title: '半导体',
    value: '半导体',
    key: '半导体',
  },
  {
    title: '芯片',
    value: '芯片',
    key: '芯片',
  },
  {
    title: '两会',
    value: '两会',
    key: '两会',
  },
  {
    title: '一带一路',
    value: '一带一路',
    key: '一带一路',
  },
];
